name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-help:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run script help
        run: python inventory_cli.py --help
